/////////// NOTICE ///////////
// This file is autogenerated from Kotlin classes via the Gradle task generateTypescriptDefinitions.
// Please refer to and edit the original, io.github.JMoore34_CSweetman.SerializableClasses.

interface CardsPlayed {
    cards: string[];
    playerID: number | undefined;
}

interface Player {
    id: number;
    judgeRole: string | undefined;
    name: string;
    presentedHand: string[];
    rolesWon: string[];
}

interface SerializableRoomInfo {
    judgePlayerID: number;
    judgeRole: string;
    playerList: Player[];
}

interface CurrentState {
    playerID: number;
    roomData: SerializableRoomInfo;
}

interface EndOfRound {
    newCards: string[];
    roleCards: string[] | undefined;
    winnerPlayerID: number | undefined;
}

interface PlayerJoined {
    newPlayer: Player;
}

interface PlayerLeft {
    playerID: number;
}

interface SelectionOfRole {
    judgeID: number | undefined;
    role: string;
}

interface SetName {
    name: string;
    playerID: number | undefined;
}

interface Message {
    cardsPlayed: CardsPlayed | undefined;
    currentState: CurrentState | undefined;
    endOfRound: EndOfRound | undefined;
    playerJoined: PlayerJoined | undefined;
    playerLeft: PlayerLeft | undefined;
    selectionOfRole: SelectionOfRole | undefined;
    setName: SetName | undefined;
}