/////////// NOTICE ///////////
// This file is autogenerated from Kotlin classes via the Gradle task generateTypescriptDefinitions.
// Please refer to and edit the original, io.github.JMoore34_CSweetman.SerializableClasses.

interface Player {
    id: number;
    name: string;
    rolesWon: string[];
}

interface PlayerJoined {
    newPlayer: Player;
}

interface Message {
    playerJoinedMessage: PlayerJoined | undefined;
}

interface Room {
    playerList: Player[];
}